#pragma once
#ifndef P3D_ECS_ALL_COMPONENTS_H
#define P3D_ECS_ALL_COMPONENTS_H
// AUTOGENERATED. DO NOT EDIT!

#ifndef INTERROGATE
#include "components.pb.h"

class Entity;

void deserialize_components(Entity* entity, const p3d_ecs::proto::Components& components);

#endif
#endif
