// AUTOGENERATED. DO NOT EDIT!

#include "all_components_gen.h"
#include "entity.h"

#include "transform_component.h"
#include "transform_component_meta.pb.h"
#include "physics_component.h"
#include "physics_component_meta.pb.h"

void
deserialize_components(Entity* entity, const p3d_ecs::proto::Components& components) {

  if (components.has_transform_component()) {
    TransformComponent& component = entity->new_component<TransformComponent>();
    component.deserialize(components.transform_component());
  }

  if (components.has_physics_component()) {
    PhysicsComponent& component = entity->new_component<PhysicsComponent>();
    component.deserialize(components.physics_component());
  }
}
