// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components_gen/physics_component_meta.proto

#ifndef PROTOBUF_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto__INCLUDED
#define PROTOBUF_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
// @@protoc_insertion_point(includes)

namespace p3d_ecs {
  namespace proto {

    // Internal implementation detail -- do not call these.
    void protobuf_AddDesc_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto();
    void protobuf_InitDefaults_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto();
    void protobuf_AssignDesc_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto();
    void protobuf_ShutdownFile_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto();

    class PhysicsComponent;

    // ===================================================================

    class PhysicsComponent
      : public ::google::protobuf::
          Message /* @@protoc_insertion_point(class_definition:p3d_ecs.proto.PhysicsComponent) */ {
    public:
      PhysicsComponent();
      virtual ~PhysicsComponent();

      PhysicsComponent(const PhysicsComponent& from);

      inline PhysicsComponent& operator=(const PhysicsComponent& from) {
        CopyFrom(from);
        return *this;
      }

      static const ::google::protobuf::Descriptor* descriptor();
      static const PhysicsComponent& default_instance();

      static const PhysicsComponent* internal_default_instance();

      void Swap(PhysicsComponent* other);

      // implements Message ----------------------------------------------

      inline PhysicsComponent* New() const { return New(NULL); }

      PhysicsComponent* New(::google::protobuf::Arena* arena) const;
      void CopyFrom(const ::google::protobuf::Message& from);
      void MergeFrom(const ::google::protobuf::Message& from);
      void CopyFrom(const PhysicsComponent& from);
      void MergeFrom(const PhysicsComponent& from);
      void Clear();
      bool IsInitialized() const;

      size_t ByteSizeLong() const;
      bool MergePartialFromCodedStream(::google::protobuf::io::CodedInputStream* input);
      void SerializeWithCachedSizes(::google::protobuf::io::CodedOutputStream* output) const;
      ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
        bool deterministic, ::google::protobuf::uint8* output) const;
      ::google::protobuf::uint8* SerializeWithCachedSizesToArray(
        ::google::protobuf::uint8* output) const {
        return InternalSerializeWithCachedSizesToArray(false, output);
      }
      int GetCachedSize() const { return _cached_size_; }

    private:
      void SharedCtor();
      void SharedDtor();
      void SetCachedSize(int size) const;
      void InternalSwap(PhysicsComponent* other);
      void UnsafeMergeFrom(const PhysicsComponent& from);

    private:
      inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
        return _internal_metadata_.arena();
      }
      inline void* MaybeArenaPtr() const { return _internal_metadata_.raw_arena_ptr(); }

    public:
      ::google::protobuf::Metadata GetMetadata() const;

      // nested types ----------------------------------------------------

      // accessors -------------------------------------------------------

      // optional .google.protobuf.FloatValue mass = 1;
      bool has_mass() const;
      void clear_mass();
      static const int kMassFieldNumber = 1;
      const ::google::protobuf::FloatValue& mass() const;
      ::google::protobuf::FloatValue* mutable_mass();
      ::google::protobuf::FloatValue* release_mass();
      void set_allocated_mass(::google::protobuf::FloatValue* mass);

      // optional .google.protobuf.BoolValue is_static = 2;
      bool has_is_static() const;
      void clear_is_static();
      static const int kIsStaticFieldNumber = 2;
      const ::google::protobuf::BoolValue& is_static() const;
      ::google::protobuf::BoolValue* mutable_is_static();
      ::google::protobuf::BoolValue* release_is_static();
      void set_allocated_is_static(::google::protobuf::BoolValue* is_static);

      // @@protoc_insertion_point(class_scope:p3d_ecs.proto.PhysicsComponent)
    private:
      ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
      ::google::protobuf::FloatValue* mass_;
      ::google::protobuf::BoolValue* is_static_;
      mutable int _cached_size_;
      friend void
      protobuf_InitDefaults_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto_impl();
      friend void protobuf_AddDesc_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto_impl();
      friend void protobuf_AssignDesc_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto();
      friend void protobuf_ShutdownFile_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto();

      void InitAsDefaultInstance();
    };
    extern ::google::protobuf::internal::ExplicitlyConstructed<PhysicsComponent>
      PhysicsComponent_default_instance_;

// ===================================================================

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
    // PhysicsComponent

    // optional .google.protobuf.FloatValue mass = 1;
    inline bool PhysicsComponent::has_mass() const {
      return this != internal_default_instance() && mass_ != NULL;
    }
    inline void PhysicsComponent::clear_mass() {
      if (GetArenaNoVirtual() == NULL && mass_ != NULL)
        delete mass_;
      mass_ = NULL;
    }
    inline const ::google::protobuf::FloatValue& PhysicsComponent::mass() const {
      // @@protoc_insertion_point(field_get:p3d_ecs.proto.PhysicsComponent.mass)
      return mass_ != NULL ? *mass_ : *::google::protobuf::FloatValue::internal_default_instance();
    }
    inline ::google::protobuf::FloatValue* PhysicsComponent::mutable_mass() {

      if (mass_ == NULL) {
        mass_ = new ::google::protobuf::FloatValue;
      }
      // @@protoc_insertion_point(field_mutable:p3d_ecs.proto.PhysicsComponent.mass)
      return mass_;
    }
    inline ::google::protobuf::FloatValue* PhysicsComponent::release_mass() {
      // @@protoc_insertion_point(field_release:p3d_ecs.proto.PhysicsComponent.mass)

      ::google::protobuf::FloatValue* temp = mass_;
      mass_ = NULL;
      return temp;
    }
    inline void PhysicsComponent::set_allocated_mass(::google::protobuf::FloatValue* mass) {
      delete mass_;
      if (mass != NULL && mass->GetArena() != NULL) {
        ::google::protobuf::FloatValue* new_mass = new ::google::protobuf::FloatValue;
        new_mass->CopyFrom(*mass);
        mass = new_mass;
      }
      mass_ = mass;
      if (mass) {

      } else {
      }
      // @@protoc_insertion_point(field_set_allocated:p3d_ecs.proto.PhysicsComponent.mass)
    }

    // optional .google.protobuf.BoolValue is_static = 2;
    inline bool PhysicsComponent::has_is_static() const {
      return this != internal_default_instance() && is_static_ != NULL;
    }
    inline void PhysicsComponent::clear_is_static() {
      if (GetArenaNoVirtual() == NULL && is_static_ != NULL)
        delete is_static_;
      is_static_ = NULL;
    }
    inline const ::google::protobuf::BoolValue& PhysicsComponent::is_static() const {
      // @@protoc_insertion_point(field_get:p3d_ecs.proto.PhysicsComponent.is_static)
      return is_static_ != NULL ? *is_static_
                                : *::google::protobuf::BoolValue::internal_default_instance();
    }
    inline ::google::protobuf::BoolValue* PhysicsComponent::mutable_is_static() {

      if (is_static_ == NULL) {
        is_static_ = new ::google::protobuf::BoolValue;
      }
      // @@protoc_insertion_point(field_mutable:p3d_ecs.proto.PhysicsComponent.is_static)
      return is_static_;
    }
    inline ::google::protobuf::BoolValue* PhysicsComponent::release_is_static() {
      // @@protoc_insertion_point(field_release:p3d_ecs.proto.PhysicsComponent.is_static)

      ::google::protobuf::BoolValue* temp = is_static_;
      is_static_ = NULL;
      return temp;
    }
    inline void PhysicsComponent::set_allocated_is_static(
      ::google::protobuf::BoolValue* is_static) {
      delete is_static_;
      if (is_static != NULL && is_static->GetArena() != NULL) {
        ::google::protobuf::BoolValue* new_is_static = new ::google::protobuf::BoolValue;
        new_is_static->CopyFrom(*is_static);
        is_static = new_is_static;
      }
      is_static_ = is_static;
      if (is_static) {

      } else {
      }
      // @@protoc_insertion_point(field_set_allocated:p3d_ecs.proto.PhysicsComponent.is_static)
    }

    inline const PhysicsComponent* PhysicsComponent::internal_default_instance() {
      return &PhysicsComponent_default_instance_.get();
    }
#endif // !PROTOBUF_INLINE_NOT_IN_HEADERS

    // @@protoc_insertion_point(namespace_scope)

  } // namespace proto
} // namespace p3d_ecs

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_components_5fgen_2fphysics_5fcomponent_5fmeta_2eproto__INCLUDED
