// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: components_gen/transform_component_meta.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "components_gen/transform_component_meta.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace p3d_ecs {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* TransformComponent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TransformComponent_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto() {
  protobuf_AddDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "components_gen/transform_component_meta.proto");
  GOOGLE_CHECK(file != NULL);
  TransformComponent_descriptor_ = file->message_type(0);
  static const int TransformComponent_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransformComponent, matrix_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransformComponent, parent_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransformComponent, children_),
  };
  TransformComponent_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TransformComponent_descriptor_,
      TransformComponent::internal_default_instance(),
      TransformComponent_offsets_,
      -1,
      -1,
      -1,
      sizeof(TransformComponent),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransformComponent, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TransformComponent_descriptor_, TransformComponent::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto() {
  TransformComponent_default_instance_.Shutdown();
  delete TransformComponent_reflection_;
}

void protobuf_InitDefaults_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::p3d_ecs::proto::protobuf_InitDefaults_component_5ftypes_2fluse_2eproto();
  ::google::protobuf::internal::GetEmptyString();
  TransformComponent_default_instance_.DefaultConstruct();
  TransformComponent_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_once_);
void protobuf_InitDefaults_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_once_,
                 &protobuf_InitDefaults_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_impl);
}
void protobuf_AddDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n-components_gen/transform_component_met"
    "a.proto\022\rp3d_ecs.proto\032\032component_types/"
    "luse.proto\"`\n\022TransformComponent\022(\n\006matr"
    "ix\030\001 \001(\0132\030.p3d_ecs.proto.LMatrix4f\022\016\n\006pa"
    "rent\030\002 \001(\014\022\020\n\010children\030\003 \003(\014b\006proto3", 196);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "components_gen/transform_component_meta.proto", &protobuf_RegisterTypes);
  ::p3d_ecs::proto::protobuf_AddDesc_component_5ftypes_2fluse_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_once_);
void protobuf_AddDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_once_,
                 &protobuf_AddDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto {
  StaticDescriptorInitializer_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto() {
    protobuf_AddDesc_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto();
  }
} static_descriptor_initializer_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TransformComponent::kMatrixFieldNumber;
const int TransformComponent::kParentFieldNumber;
const int TransformComponent::kChildrenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TransformComponent::TransformComponent()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:p3d_ecs.proto.TransformComponent)
}

void TransformComponent::InitAsDefaultInstance() {
  matrix_ = const_cast< ::p3d_ecs::proto::LMatrix4f*>(
      ::p3d_ecs::proto::LMatrix4f::internal_default_instance());
}

TransformComponent::TransformComponent(const TransformComponent& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:p3d_ecs.proto.TransformComponent)
}

void TransformComponent::SharedCtor() {
  parent_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  matrix_ = NULL;
  _cached_size_ = 0;
}

TransformComponent::~TransformComponent() {
  // @@protoc_insertion_point(destructor:p3d_ecs.proto.TransformComponent)
  SharedDtor();
}

void TransformComponent::SharedDtor() {
  parent_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != &TransformComponent_default_instance_.get()) {
    delete matrix_;
  }
}

void TransformComponent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TransformComponent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TransformComponent_descriptor_;
}

const TransformComponent& TransformComponent::default_instance() {
  protobuf_InitDefaults_components_5fgen_2ftransform_5fcomponent_5fmeta_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<TransformComponent> TransformComponent_default_instance_;

TransformComponent* TransformComponent::New(::google::protobuf::Arena* arena) const {
  TransformComponent* n = new TransformComponent;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TransformComponent::Clear() {
// @@protoc_insertion_point(message_clear_start:p3d_ecs.proto.TransformComponent)
  if (GetArenaNoVirtual() == NULL && matrix_ != NULL) delete matrix_;
  matrix_ = NULL;
  parent_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  children_.Clear();
}

bool TransformComponent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:p3d_ecs.proto.TransformComponent)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .p3d_ecs.proto.LMatrix4f matrix = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_matrix()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_parent;
        break;
      }

      // optional bytes parent = 2;
      case 2: {
        if (tag == 18) {
         parse_parent:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_parent()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_children;
        break;
      }

      // repeated bytes children = 3;
      case 3: {
        if (tag == 26) {
         parse_children:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_children()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_children;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:p3d_ecs.proto.TransformComponent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:p3d_ecs.proto.TransformComponent)
  return false;
#undef DO_
}

void TransformComponent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:p3d_ecs.proto.TransformComponent)
  // optional .p3d_ecs.proto.LMatrix4f matrix = 1;
  if (this->has_matrix()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->matrix_, output);
  }

  // optional bytes parent = 2;
  if (this->parent().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->parent(), output);
  }

  // repeated bytes children = 3;
  for (int i = 0; i < this->children_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->children(i), output);
  }

  // @@protoc_insertion_point(serialize_end:p3d_ecs.proto.TransformComponent)
}

::google::protobuf::uint8* TransformComponent::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:p3d_ecs.proto.TransformComponent)
  // optional .p3d_ecs.proto.LMatrix4f matrix = 1;
  if (this->has_matrix()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->matrix_, false, target);
  }

  // optional bytes parent = 2;
  if (this->parent().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->parent(), target);
  }

  // repeated bytes children = 3;
  for (int i = 0; i < this->children_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(3, this->children(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:p3d_ecs.proto.TransformComponent)
  return target;
}

size_t TransformComponent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:p3d_ecs.proto.TransformComponent)
  size_t total_size = 0;

  // optional .p3d_ecs.proto.LMatrix4f matrix = 1;
  if (this->has_matrix()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->matrix_);
  }

  // optional bytes parent = 2;
  if (this->parent().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->parent());
  }

  // repeated bytes children = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->children_size());
  for (int i = 0; i < this->children_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->children(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TransformComponent::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:p3d_ecs.proto.TransformComponent)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const TransformComponent* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TransformComponent>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:p3d_ecs.proto.TransformComponent)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:p3d_ecs.proto.TransformComponent)
    UnsafeMergeFrom(*source);
  }
}

void TransformComponent::MergeFrom(const TransformComponent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:p3d_ecs.proto.TransformComponent)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void TransformComponent::UnsafeMergeFrom(const TransformComponent& from) {
  GOOGLE_DCHECK(&from != this);
  children_.UnsafeMergeFrom(from.children_);
  if (from.has_matrix()) {
    mutable_matrix()->::p3d_ecs::proto::LMatrix4f::MergeFrom(from.matrix());
  }
  if (from.parent().size() > 0) {

    parent_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parent_);
  }
}

void TransformComponent::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:p3d_ecs.proto.TransformComponent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TransformComponent::CopyFrom(const TransformComponent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:p3d_ecs.proto.TransformComponent)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool TransformComponent::IsInitialized() const {

  return true;
}

void TransformComponent::Swap(TransformComponent* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TransformComponent::InternalSwap(TransformComponent* other) {
  std::swap(matrix_, other->matrix_);
  parent_.Swap(&other->parent_);
  children_.UnsafeArenaSwap(&other->children_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TransformComponent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TransformComponent_descriptor_;
  metadata.reflection = TransformComponent_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TransformComponent

// optional .p3d_ecs.proto.LMatrix4f matrix = 1;
bool TransformComponent::has_matrix() const {
  return this != internal_default_instance() && matrix_ != NULL;
}
void TransformComponent::clear_matrix() {
  if (GetArenaNoVirtual() == NULL && matrix_ != NULL) delete matrix_;
  matrix_ = NULL;
}
const ::p3d_ecs::proto::LMatrix4f& TransformComponent::matrix() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.TransformComponent.matrix)
  return matrix_ != NULL ? *matrix_
                         : *::p3d_ecs::proto::LMatrix4f::internal_default_instance();
}
::p3d_ecs::proto::LMatrix4f* TransformComponent::mutable_matrix() {
  
  if (matrix_ == NULL) {
    matrix_ = new ::p3d_ecs::proto::LMatrix4f;
  }
  // @@protoc_insertion_point(field_mutable:p3d_ecs.proto.TransformComponent.matrix)
  return matrix_;
}
::p3d_ecs::proto::LMatrix4f* TransformComponent::release_matrix() {
  // @@protoc_insertion_point(field_release:p3d_ecs.proto.TransformComponent.matrix)
  
  ::p3d_ecs::proto::LMatrix4f* temp = matrix_;
  matrix_ = NULL;
  return temp;
}
void TransformComponent::set_allocated_matrix(::p3d_ecs::proto::LMatrix4f* matrix) {
  delete matrix_;
  matrix_ = matrix;
  if (matrix) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:p3d_ecs.proto.TransformComponent.matrix)
}

// optional bytes parent = 2;
void TransformComponent::clear_parent() {
  parent_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& TransformComponent::parent() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.TransformComponent.parent)
  return parent_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransformComponent::set_parent(const ::std::string& value) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.TransformComponent.parent)
}
void TransformComponent::set_parent(const char* value) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:p3d_ecs.proto.TransformComponent.parent)
}
void TransformComponent::set_parent(const void* value, size_t size) {
  
  parent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:p3d_ecs.proto.TransformComponent.parent)
}
::std::string* TransformComponent::mutable_parent() {
  
  // @@protoc_insertion_point(field_mutable:p3d_ecs.proto.TransformComponent.parent)
  return parent_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TransformComponent::release_parent() {
  // @@protoc_insertion_point(field_release:p3d_ecs.proto.TransformComponent.parent)
  
  return parent_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TransformComponent::set_allocated_parent(::std::string* parent) {
  if (parent != NULL) {
    
  } else {
    
  }
  parent_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parent);
  // @@protoc_insertion_point(field_set_allocated:p3d_ecs.proto.TransformComponent.parent)
}

// repeated bytes children = 3;
int TransformComponent::children_size() const {
  return children_.size();
}
void TransformComponent::clear_children() {
  children_.Clear();
}
const ::std::string& TransformComponent::children(int index) const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.TransformComponent.children)
  return children_.Get(index);
}
::std::string* TransformComponent::mutable_children(int index) {
  // @@protoc_insertion_point(field_mutable:p3d_ecs.proto.TransformComponent.children)
  return children_.Mutable(index);
}
void TransformComponent::set_children(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.TransformComponent.children)
  children_.Mutable(index)->assign(value);
}
void TransformComponent::set_children(int index, const char* value) {
  children_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:p3d_ecs.proto.TransformComponent.children)
}
void TransformComponent::set_children(int index, const void* value, size_t size) {
  children_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:p3d_ecs.proto.TransformComponent.children)
}
::std::string* TransformComponent::add_children() {
  // @@protoc_insertion_point(field_add_mutable:p3d_ecs.proto.TransformComponent.children)
  return children_.Add();
}
void TransformComponent::add_children(const ::std::string& value) {
  children_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:p3d_ecs.proto.TransformComponent.children)
}
void TransformComponent::add_children(const char* value) {
  children_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:p3d_ecs.proto.TransformComponent.children)
}
void TransformComponent::add_children(const void* value, size_t size) {
  children_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:p3d_ecs.proto.TransformComponent.children)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
TransformComponent::children() const {
  // @@protoc_insertion_point(field_list:p3d_ecs.proto.TransformComponent.children)
  return children_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
TransformComponent::mutable_children() {
  // @@protoc_insertion_point(field_mutable_list:p3d_ecs.proto.TransformComponent.children)
  return &children_;
}

inline const TransformComponent* TransformComponent::internal_default_instance() {
  return &TransformComponent_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace p3d_ecs

// @@protoc_insertion_point(global_scope)
