// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: component_types/luse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "component_types/luse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace p3d_ecs {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* LVecBase3f_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LVecBase3f_reflection_ = NULL;
const ::google::protobuf::Descriptor* LMatrix4f_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LMatrix4f_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_component_5ftypes_2fluse_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_component_5ftypes_2fluse_2eproto() {
  protobuf_AddDesc_component_5ftypes_2fluse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "component_types/luse.proto");
  GOOGLE_CHECK(file != NULL);
  LVecBase3f_descriptor_ = file->message_type(0);
  static const int LVecBase3f_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LVecBase3f, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LVecBase3f, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LVecBase3f, z_),
  };
  LVecBase3f_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LVecBase3f_descriptor_,
      LVecBase3f::internal_default_instance(),
      LVecBase3f_offsets_,
      -1,
      -1,
      -1,
      sizeof(LVecBase3f),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LVecBase3f, _internal_metadata_));
  LMatrix4f_descriptor_ = file->message_type(1);
  static const int LMatrix4f_offsets_[16] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_0_0_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_0_1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_0_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_0_3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_1_0_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_1_1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_1_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_1_3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_2_0_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_2_1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_2_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_2_3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_3_0_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_3_1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_3_2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, m_3_3_),
  };
  LMatrix4f_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LMatrix4f_descriptor_,
      LMatrix4f::internal_default_instance(),
      LMatrix4f_offsets_,
      -1,
      -1,
      -1,
      sizeof(LMatrix4f),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LMatrix4f, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_component_5ftypes_2fluse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LVecBase3f_descriptor_, LVecBase3f::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LMatrix4f_descriptor_, LMatrix4f::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_component_5ftypes_2fluse_2eproto() {
  LVecBase3f_default_instance_.Shutdown();
  delete LVecBase3f_reflection_;
  LMatrix4f_default_instance_.Shutdown();
  delete LMatrix4f_reflection_;
}

void protobuf_InitDefaults_component_5ftypes_2fluse_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  LVecBase3f_default_instance_.DefaultConstruct();
  LMatrix4f_default_instance_.DefaultConstruct();
  LVecBase3f_default_instance_.get_mutable()->InitAsDefaultInstance();
  LMatrix4f_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_component_5ftypes_2fluse_2eproto_once_);
void protobuf_InitDefaults_component_5ftypes_2fluse_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_component_5ftypes_2fluse_2eproto_once_,
                 &protobuf_InitDefaults_component_5ftypes_2fluse_2eproto_impl);
}
void protobuf_AddDesc_component_5ftypes_2fluse_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_component_5ftypes_2fluse_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032component_types/luse.proto\022\rp3d_ecs.pr"
    "oto\"-\n\nLVecBase3f\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022"
    "\t\n\001z\030\003 \001(\002\"\373\001\n\tLMatrix4f\022\r\n\005m_0_0\030\001 \001(\002\022"
    "\r\n\005m_0_1\030\002 \001(\002\022\r\n\005m_0_2\030\003 \001(\002\022\r\n\005m_0_3\030\004"
    " \001(\002\022\r\n\005m_1_0\030\005 \001(\002\022\r\n\005m_1_1\030\006 \001(\002\022\r\n\005m_"
    "1_2\030\007 \001(\002\022\r\n\005m_1_3\030\010 \001(\002\022\r\n\005m_2_0\030\t \001(\002\022"
    "\r\n\005m_2_1\030\n \001(\002\022\r\n\005m_2_2\030\013 \001(\002\022\r\n\005m_2_3\030\014"
    " \001(\002\022\r\n\005m_3_0\030\r \001(\002\022\r\n\005m_3_1\030\016 \001(\002\022\r\n\005m_"
    "3_2\030\017 \001(\002\022\r\n\005m_3_3\030\020 \001(\002b\006proto3", 352);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "component_types/luse.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_component_5ftypes_2fluse_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_component_5ftypes_2fluse_2eproto_once_);
void protobuf_AddDesc_component_5ftypes_2fluse_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_component_5ftypes_2fluse_2eproto_once_,
                 &protobuf_AddDesc_component_5ftypes_2fluse_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_component_5ftypes_2fluse_2eproto {
  StaticDescriptorInitializer_component_5ftypes_2fluse_2eproto() {
    protobuf_AddDesc_component_5ftypes_2fluse_2eproto();
  }
} static_descriptor_initializer_component_5ftypes_2fluse_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LVecBase3f::kXFieldNumber;
const int LVecBase3f::kYFieldNumber;
const int LVecBase3f::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LVecBase3f::LVecBase3f()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_component_5ftypes_2fluse_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:p3d_ecs.proto.LVecBase3f)
}

void LVecBase3f::InitAsDefaultInstance() {
}

LVecBase3f::LVecBase3f(const LVecBase3f& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:p3d_ecs.proto.LVecBase3f)
}

void LVecBase3f::SharedCtor() {
  ::memset(&x_, 0, reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_) + sizeof(z_));
  _cached_size_ = 0;
}

LVecBase3f::~LVecBase3f() {
  // @@protoc_insertion_point(destructor:p3d_ecs.proto.LVecBase3f)
  SharedDtor();
}

void LVecBase3f::SharedDtor() {
}

void LVecBase3f::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LVecBase3f::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LVecBase3f_descriptor_;
}

const LVecBase3f& LVecBase3f::default_instance() {
  protobuf_InitDefaults_component_5ftypes_2fluse_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<LVecBase3f> LVecBase3f_default_instance_;

LVecBase3f* LVecBase3f::New(::google::protobuf::Arena* arena) const {
  LVecBase3f* n = new LVecBase3f;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LVecBase3f::Clear() {
// @@protoc_insertion_point(message_clear_start:p3d_ecs.proto.LVecBase3f)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(LVecBase3f, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<LVecBase3f*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&(first), 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(x_, z_);

#undef ZR_HELPER_
#undef ZR_

}

bool LVecBase3f::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:p3d_ecs.proto.LVecBase3f)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float x = 1;
      case 1: {
        if (tag == 13) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_y;
        break;
      }

      // optional float y = 2;
      case 2: {
        if (tag == 21) {
         parse_y:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_z;
        break;
      }

      // optional float z = 3;
      case 3: {
        if (tag == 29) {
         parse_z:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:p3d_ecs.proto.LVecBase3f)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:p3d_ecs.proto.LVecBase3f)
  return false;
#undef DO_
}

void LVecBase3f::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:p3d_ecs.proto.LVecBase3f)
  // optional float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // optional float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // optional float z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  // @@protoc_insertion_point(serialize_end:p3d_ecs.proto.LVecBase3f)
}

::google::protobuf::uint8* LVecBase3f::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:p3d_ecs.proto.LVecBase3f)
  // optional float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // optional float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // optional float z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:p3d_ecs.proto.LVecBase3f)
  return target;
}

size_t LVecBase3f::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:p3d_ecs.proto.LVecBase3f)
  size_t total_size = 0;

  // optional float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // optional float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // optional float z = 3;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LVecBase3f::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:p3d_ecs.proto.LVecBase3f)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const LVecBase3f* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LVecBase3f>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:p3d_ecs.proto.LVecBase3f)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:p3d_ecs.proto.LVecBase3f)
    UnsafeMergeFrom(*source);
  }
}

void LVecBase3f::MergeFrom(const LVecBase3f& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:p3d_ecs.proto.LVecBase3f)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void LVecBase3f::UnsafeMergeFrom(const LVecBase3f& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
}

void LVecBase3f::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:p3d_ecs.proto.LVecBase3f)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LVecBase3f::CopyFrom(const LVecBase3f& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:p3d_ecs.proto.LVecBase3f)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool LVecBase3f::IsInitialized() const {

  return true;
}

void LVecBase3f::Swap(LVecBase3f* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LVecBase3f::InternalSwap(LVecBase3f* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LVecBase3f::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LVecBase3f_descriptor_;
  metadata.reflection = LVecBase3f_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LVecBase3f

// optional float x = 1;
void LVecBase3f::clear_x() {
  x_ = 0;
}
float LVecBase3f::x() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LVecBase3f.x)
  return x_;
}
void LVecBase3f::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LVecBase3f.x)
}

// optional float y = 2;
void LVecBase3f::clear_y() {
  y_ = 0;
}
float LVecBase3f::y() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LVecBase3f.y)
  return y_;
}
void LVecBase3f::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LVecBase3f.y)
}

// optional float z = 3;
void LVecBase3f::clear_z() {
  z_ = 0;
}
float LVecBase3f::z() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LVecBase3f.z)
  return z_;
}
void LVecBase3f::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LVecBase3f.z)
}

inline const LVecBase3f* LVecBase3f::internal_default_instance() {
  return &LVecBase3f_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LMatrix4f::kM00FieldNumber;
const int LMatrix4f::kM01FieldNumber;
const int LMatrix4f::kM02FieldNumber;
const int LMatrix4f::kM03FieldNumber;
const int LMatrix4f::kM10FieldNumber;
const int LMatrix4f::kM11FieldNumber;
const int LMatrix4f::kM12FieldNumber;
const int LMatrix4f::kM13FieldNumber;
const int LMatrix4f::kM20FieldNumber;
const int LMatrix4f::kM21FieldNumber;
const int LMatrix4f::kM22FieldNumber;
const int LMatrix4f::kM23FieldNumber;
const int LMatrix4f::kM30FieldNumber;
const int LMatrix4f::kM31FieldNumber;
const int LMatrix4f::kM32FieldNumber;
const int LMatrix4f::kM33FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LMatrix4f::LMatrix4f()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_component_5ftypes_2fluse_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:p3d_ecs.proto.LMatrix4f)
}

void LMatrix4f::InitAsDefaultInstance() {
}

LMatrix4f::LMatrix4f(const LMatrix4f& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:p3d_ecs.proto.LMatrix4f)
}

void LMatrix4f::SharedCtor() {
  ::memset(&m_0_0_, 0, reinterpret_cast<char*>(&m_3_3_) -
    reinterpret_cast<char*>(&m_0_0_) + sizeof(m_3_3_));
  _cached_size_ = 0;
}

LMatrix4f::~LMatrix4f() {
  // @@protoc_insertion_point(destructor:p3d_ecs.proto.LMatrix4f)
  SharedDtor();
}

void LMatrix4f::SharedDtor() {
}

void LMatrix4f::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LMatrix4f::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LMatrix4f_descriptor_;
}

const LMatrix4f& LMatrix4f::default_instance() {
  protobuf_InitDefaults_component_5ftypes_2fluse_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<LMatrix4f> LMatrix4f_default_instance_;

LMatrix4f* LMatrix4f::New(::google::protobuf::Arena* arena) const {
  LMatrix4f* n = new LMatrix4f;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LMatrix4f::Clear() {
// @@protoc_insertion_point(message_clear_start:p3d_ecs.proto.LMatrix4f)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(LMatrix4f, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<LMatrix4f*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&(first), 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(m_0_0_, m_1_3_);
  ZR_(m_2_0_, m_3_3_);

#undef ZR_HELPER_
#undef ZR_

}

bool LMatrix4f::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:p3d_ecs.proto.LMatrix4f)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float m_0_0 = 1;
      case 1: {
        if (tag == 13) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_0_0_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_m_0_1;
        break;
      }

      // optional float m_0_1 = 2;
      case 2: {
        if (tag == 21) {
         parse_m_0_1:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_0_1_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_m_0_2;
        break;
      }

      // optional float m_0_2 = 3;
      case 3: {
        if (tag == 29) {
         parse_m_0_2:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_0_2_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_m_0_3;
        break;
      }

      // optional float m_0_3 = 4;
      case 4: {
        if (tag == 37) {
         parse_m_0_3:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_0_3_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(45)) goto parse_m_1_0;
        break;
      }

      // optional float m_1_0 = 5;
      case 5: {
        if (tag == 45) {
         parse_m_1_0:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_1_0_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(53)) goto parse_m_1_1;
        break;
      }

      // optional float m_1_1 = 6;
      case 6: {
        if (tag == 53) {
         parse_m_1_1:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_1_1_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(61)) goto parse_m_1_2;
        break;
      }

      // optional float m_1_2 = 7;
      case 7: {
        if (tag == 61) {
         parse_m_1_2:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_1_2_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(69)) goto parse_m_1_3;
        break;
      }

      // optional float m_1_3 = 8;
      case 8: {
        if (tag == 69) {
         parse_m_1_3:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_1_3_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(77)) goto parse_m_2_0;
        break;
      }

      // optional float m_2_0 = 9;
      case 9: {
        if (tag == 77) {
         parse_m_2_0:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_2_0_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(85)) goto parse_m_2_1;
        break;
      }

      // optional float m_2_1 = 10;
      case 10: {
        if (tag == 85) {
         parse_m_2_1:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_2_1_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(93)) goto parse_m_2_2;
        break;
      }

      // optional float m_2_2 = 11;
      case 11: {
        if (tag == 93) {
         parse_m_2_2:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_2_2_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(101)) goto parse_m_2_3;
        break;
      }

      // optional float m_2_3 = 12;
      case 12: {
        if (tag == 101) {
         parse_m_2_3:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_2_3_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(109)) goto parse_m_3_0;
        break;
      }

      // optional float m_3_0 = 13;
      case 13: {
        if (tag == 109) {
         parse_m_3_0:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_3_0_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(117)) goto parse_m_3_1;
        break;
      }

      // optional float m_3_1 = 14;
      case 14: {
        if (tag == 117) {
         parse_m_3_1:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_3_1_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(125)) goto parse_m_3_2;
        break;
      }

      // optional float m_3_2 = 15;
      case 15: {
        if (tag == 125) {
         parse_m_3_2:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_3_2_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(133)) goto parse_m_3_3;
        break;
      }

      // optional float m_3_3 = 16;
      case 16: {
        if (tag == 133) {
         parse_m_3_3:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &m_3_3_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:p3d_ecs.proto.LMatrix4f)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:p3d_ecs.proto.LMatrix4f)
  return false;
#undef DO_
}

void LMatrix4f::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:p3d_ecs.proto.LMatrix4f)
  // optional float m_0_0 = 1;
  if (this->m_0_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->m_0_0(), output);
  }

  // optional float m_0_1 = 2;
  if (this->m_0_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->m_0_1(), output);
  }

  // optional float m_0_2 = 3;
  if (this->m_0_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->m_0_2(), output);
  }

  // optional float m_0_3 = 4;
  if (this->m_0_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->m_0_3(), output);
  }

  // optional float m_1_0 = 5;
  if (this->m_1_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->m_1_0(), output);
  }

  // optional float m_1_1 = 6;
  if (this->m_1_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->m_1_1(), output);
  }

  // optional float m_1_2 = 7;
  if (this->m_1_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->m_1_2(), output);
  }

  // optional float m_1_3 = 8;
  if (this->m_1_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->m_1_3(), output);
  }

  // optional float m_2_0 = 9;
  if (this->m_2_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(9, this->m_2_0(), output);
  }

  // optional float m_2_1 = 10;
  if (this->m_2_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(10, this->m_2_1(), output);
  }

  // optional float m_2_2 = 11;
  if (this->m_2_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(11, this->m_2_2(), output);
  }

  // optional float m_2_3 = 12;
  if (this->m_2_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(12, this->m_2_3(), output);
  }

  // optional float m_3_0 = 13;
  if (this->m_3_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(13, this->m_3_0(), output);
  }

  // optional float m_3_1 = 14;
  if (this->m_3_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(14, this->m_3_1(), output);
  }

  // optional float m_3_2 = 15;
  if (this->m_3_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(15, this->m_3_2(), output);
  }

  // optional float m_3_3 = 16;
  if (this->m_3_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(16, this->m_3_3(), output);
  }

  // @@protoc_insertion_point(serialize_end:p3d_ecs.proto.LMatrix4f)
}

::google::protobuf::uint8* LMatrix4f::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:p3d_ecs.proto.LMatrix4f)
  // optional float m_0_0 = 1;
  if (this->m_0_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->m_0_0(), target);
  }

  // optional float m_0_1 = 2;
  if (this->m_0_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->m_0_1(), target);
  }

  // optional float m_0_2 = 3;
  if (this->m_0_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->m_0_2(), target);
  }

  // optional float m_0_3 = 4;
  if (this->m_0_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->m_0_3(), target);
  }

  // optional float m_1_0 = 5;
  if (this->m_1_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->m_1_0(), target);
  }

  // optional float m_1_1 = 6;
  if (this->m_1_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->m_1_1(), target);
  }

  // optional float m_1_2 = 7;
  if (this->m_1_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->m_1_2(), target);
  }

  // optional float m_1_3 = 8;
  if (this->m_1_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->m_1_3(), target);
  }

  // optional float m_2_0 = 9;
  if (this->m_2_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(9, this->m_2_0(), target);
  }

  // optional float m_2_1 = 10;
  if (this->m_2_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(10, this->m_2_1(), target);
  }

  // optional float m_2_2 = 11;
  if (this->m_2_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(11, this->m_2_2(), target);
  }

  // optional float m_2_3 = 12;
  if (this->m_2_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(12, this->m_2_3(), target);
  }

  // optional float m_3_0 = 13;
  if (this->m_3_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(13, this->m_3_0(), target);
  }

  // optional float m_3_1 = 14;
  if (this->m_3_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(14, this->m_3_1(), target);
  }

  // optional float m_3_2 = 15;
  if (this->m_3_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(15, this->m_3_2(), target);
  }

  // optional float m_3_3 = 16;
  if (this->m_3_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(16, this->m_3_3(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:p3d_ecs.proto.LMatrix4f)
  return target;
}

size_t LMatrix4f::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:p3d_ecs.proto.LMatrix4f)
  size_t total_size = 0;

  // optional float m_0_0 = 1;
  if (this->m_0_0() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_0_1 = 2;
  if (this->m_0_1() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_0_2 = 3;
  if (this->m_0_2() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_0_3 = 4;
  if (this->m_0_3() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_1_0 = 5;
  if (this->m_1_0() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_1_1 = 6;
  if (this->m_1_1() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_1_2 = 7;
  if (this->m_1_2() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_1_3 = 8;
  if (this->m_1_3() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_2_0 = 9;
  if (this->m_2_0() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_2_1 = 10;
  if (this->m_2_1() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_2_2 = 11;
  if (this->m_2_2() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_2_3 = 12;
  if (this->m_2_3() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_3_0 = 13;
  if (this->m_3_0() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_3_1 = 14;
  if (this->m_3_1() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_3_2 = 15;
  if (this->m_3_2() != 0) {
    total_size += 1 + 4;
  }

  // optional float m_3_3 = 16;
  if (this->m_3_3() != 0) {
    total_size += 2 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LMatrix4f::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:p3d_ecs.proto.LMatrix4f)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const LMatrix4f* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LMatrix4f>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:p3d_ecs.proto.LMatrix4f)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:p3d_ecs.proto.LMatrix4f)
    UnsafeMergeFrom(*source);
  }
}

void LMatrix4f::MergeFrom(const LMatrix4f& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:p3d_ecs.proto.LMatrix4f)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void LMatrix4f::UnsafeMergeFrom(const LMatrix4f& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.m_0_0() != 0) {
    set_m_0_0(from.m_0_0());
  }
  if (from.m_0_1() != 0) {
    set_m_0_1(from.m_0_1());
  }
  if (from.m_0_2() != 0) {
    set_m_0_2(from.m_0_2());
  }
  if (from.m_0_3() != 0) {
    set_m_0_3(from.m_0_3());
  }
  if (from.m_1_0() != 0) {
    set_m_1_0(from.m_1_0());
  }
  if (from.m_1_1() != 0) {
    set_m_1_1(from.m_1_1());
  }
  if (from.m_1_2() != 0) {
    set_m_1_2(from.m_1_2());
  }
  if (from.m_1_3() != 0) {
    set_m_1_3(from.m_1_3());
  }
  if (from.m_2_0() != 0) {
    set_m_2_0(from.m_2_0());
  }
  if (from.m_2_1() != 0) {
    set_m_2_1(from.m_2_1());
  }
  if (from.m_2_2() != 0) {
    set_m_2_2(from.m_2_2());
  }
  if (from.m_2_3() != 0) {
    set_m_2_3(from.m_2_3());
  }
  if (from.m_3_0() != 0) {
    set_m_3_0(from.m_3_0());
  }
  if (from.m_3_1() != 0) {
    set_m_3_1(from.m_3_1());
  }
  if (from.m_3_2() != 0) {
    set_m_3_2(from.m_3_2());
  }
  if (from.m_3_3() != 0) {
    set_m_3_3(from.m_3_3());
  }
}

void LMatrix4f::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:p3d_ecs.proto.LMatrix4f)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LMatrix4f::CopyFrom(const LMatrix4f& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:p3d_ecs.proto.LMatrix4f)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool LMatrix4f::IsInitialized() const {

  return true;
}

void LMatrix4f::Swap(LMatrix4f* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LMatrix4f::InternalSwap(LMatrix4f* other) {
  std::swap(m_0_0_, other->m_0_0_);
  std::swap(m_0_1_, other->m_0_1_);
  std::swap(m_0_2_, other->m_0_2_);
  std::swap(m_0_3_, other->m_0_3_);
  std::swap(m_1_0_, other->m_1_0_);
  std::swap(m_1_1_, other->m_1_1_);
  std::swap(m_1_2_, other->m_1_2_);
  std::swap(m_1_3_, other->m_1_3_);
  std::swap(m_2_0_, other->m_2_0_);
  std::swap(m_2_1_, other->m_2_1_);
  std::swap(m_2_2_, other->m_2_2_);
  std::swap(m_2_3_, other->m_2_3_);
  std::swap(m_3_0_, other->m_3_0_);
  std::swap(m_3_1_, other->m_3_1_);
  std::swap(m_3_2_, other->m_3_2_);
  std::swap(m_3_3_, other->m_3_3_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LMatrix4f::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LMatrix4f_descriptor_;
  metadata.reflection = LMatrix4f_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LMatrix4f

// optional float m_0_0 = 1;
void LMatrix4f::clear_m_0_0() {
  m_0_0_ = 0;
}
float LMatrix4f::m_0_0() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_0_0)
  return m_0_0_;
}
void LMatrix4f::set_m_0_0(float value) {
  
  m_0_0_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_0_0)
}

// optional float m_0_1 = 2;
void LMatrix4f::clear_m_0_1() {
  m_0_1_ = 0;
}
float LMatrix4f::m_0_1() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_0_1)
  return m_0_1_;
}
void LMatrix4f::set_m_0_1(float value) {
  
  m_0_1_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_0_1)
}

// optional float m_0_2 = 3;
void LMatrix4f::clear_m_0_2() {
  m_0_2_ = 0;
}
float LMatrix4f::m_0_2() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_0_2)
  return m_0_2_;
}
void LMatrix4f::set_m_0_2(float value) {
  
  m_0_2_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_0_2)
}

// optional float m_0_3 = 4;
void LMatrix4f::clear_m_0_3() {
  m_0_3_ = 0;
}
float LMatrix4f::m_0_3() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_0_3)
  return m_0_3_;
}
void LMatrix4f::set_m_0_3(float value) {
  
  m_0_3_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_0_3)
}

// optional float m_1_0 = 5;
void LMatrix4f::clear_m_1_0() {
  m_1_0_ = 0;
}
float LMatrix4f::m_1_0() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_1_0)
  return m_1_0_;
}
void LMatrix4f::set_m_1_0(float value) {
  
  m_1_0_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_1_0)
}

// optional float m_1_1 = 6;
void LMatrix4f::clear_m_1_1() {
  m_1_1_ = 0;
}
float LMatrix4f::m_1_1() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_1_1)
  return m_1_1_;
}
void LMatrix4f::set_m_1_1(float value) {
  
  m_1_1_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_1_1)
}

// optional float m_1_2 = 7;
void LMatrix4f::clear_m_1_2() {
  m_1_2_ = 0;
}
float LMatrix4f::m_1_2() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_1_2)
  return m_1_2_;
}
void LMatrix4f::set_m_1_2(float value) {
  
  m_1_2_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_1_2)
}

// optional float m_1_3 = 8;
void LMatrix4f::clear_m_1_3() {
  m_1_3_ = 0;
}
float LMatrix4f::m_1_3() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_1_3)
  return m_1_3_;
}
void LMatrix4f::set_m_1_3(float value) {
  
  m_1_3_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_1_3)
}

// optional float m_2_0 = 9;
void LMatrix4f::clear_m_2_0() {
  m_2_0_ = 0;
}
float LMatrix4f::m_2_0() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_2_0)
  return m_2_0_;
}
void LMatrix4f::set_m_2_0(float value) {
  
  m_2_0_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_2_0)
}

// optional float m_2_1 = 10;
void LMatrix4f::clear_m_2_1() {
  m_2_1_ = 0;
}
float LMatrix4f::m_2_1() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_2_1)
  return m_2_1_;
}
void LMatrix4f::set_m_2_1(float value) {
  
  m_2_1_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_2_1)
}

// optional float m_2_2 = 11;
void LMatrix4f::clear_m_2_2() {
  m_2_2_ = 0;
}
float LMatrix4f::m_2_2() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_2_2)
  return m_2_2_;
}
void LMatrix4f::set_m_2_2(float value) {
  
  m_2_2_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_2_2)
}

// optional float m_2_3 = 12;
void LMatrix4f::clear_m_2_3() {
  m_2_3_ = 0;
}
float LMatrix4f::m_2_3() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_2_3)
  return m_2_3_;
}
void LMatrix4f::set_m_2_3(float value) {
  
  m_2_3_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_2_3)
}

// optional float m_3_0 = 13;
void LMatrix4f::clear_m_3_0() {
  m_3_0_ = 0;
}
float LMatrix4f::m_3_0() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_3_0)
  return m_3_0_;
}
void LMatrix4f::set_m_3_0(float value) {
  
  m_3_0_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_3_0)
}

// optional float m_3_1 = 14;
void LMatrix4f::clear_m_3_1() {
  m_3_1_ = 0;
}
float LMatrix4f::m_3_1() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_3_1)
  return m_3_1_;
}
void LMatrix4f::set_m_3_1(float value) {
  
  m_3_1_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_3_1)
}

// optional float m_3_2 = 15;
void LMatrix4f::clear_m_3_2() {
  m_3_2_ = 0;
}
float LMatrix4f::m_3_2() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_3_2)
  return m_3_2_;
}
void LMatrix4f::set_m_3_2(float value) {
  
  m_3_2_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_3_2)
}

// optional float m_3_3 = 16;
void LMatrix4f::clear_m_3_3() {
  m_3_3_ = 0;
}
float LMatrix4f::m_3_3() const {
  // @@protoc_insertion_point(field_get:p3d_ecs.proto.LMatrix4f.m_3_3)
  return m_3_3_;
}
void LMatrix4f::set_m_3_3(float value) {
  
  m_3_3_ = value;
  // @@protoc_insertion_point(field_set:p3d_ecs.proto.LMatrix4f.m_3_3)
}

inline const LMatrix4f* LMatrix4f::internal_default_instance() {
  return &LMatrix4f_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace p3d_ecs

// @@protoc_insertion_point(global_scope)
