#pragma once

// AUTOGENERATED. DO NOT EDIT!
// Instead modify the component meta file.

#ifndef P3D_ECS_PHYSICSCOMPONENT_METACLS_H
#define P3D_ECS_PHYSICSCOMPONENT_METACLS_H

#include "config_module.h"
#include "component.h"
#include "perf_utility.h"
#include "memory_pool.h"
#include "luse.h"

class Entity;
class EntityManager;
class PlainTextSerializer;
class PhysicsComponent;

class PhysicsComponentMeta : public Component {
  using superclass = PhysicsComponentMeta;

  public:
    DEFINE_COMPONENT_BASE();

    // AUTOGEN:: accessors
    inline const LVecBase2f& get_hpr() const { return _hpr; }
    inline void set_hpr(const LVecBase2f& val) { _hpr = val; }
	
    inline float get_mass() const { return _mass; }
    inline void set_mass(float val) { _mass = val; }


    // AUTOGEN:: serialization
    virtual void serialize(PlainTextSerializer* serializer) const override;

  protected:
    // AUTOGEN:: constructor
    inline PhysicsComponentMeta(Entity* entity) : Component(entity)
      , _mass(10.0)
      {};

    // AUTOGEN:: internal members
    LVecBase2f _hpr;
    float _mass;
};
#endif
