#pragma once

// AUTOGENERATED. DO NOT EDIT!
// Instead modify the component meta file.

#ifndef P3D_ECS_TRANSFORMCOMPONENT_METACLS_H
#define P3D_ECS_TRANSFORMCOMPONENT_METACLS_H

#include "config_module.h"
#include "component.h"
#include "perf_utility.h"
#include "memory_pool.h"
#include "luse.h"

class Entity;
class EntityManager;
class TransformComponent;

class TransformComponentMeta : public Component {
  using superclass = TransformComponentMeta;

  public:
    DEFINE_COMPONENT_BASE();

    // AUTOGEN:: accessors
    inline const std::vector<Entity*>& get_children() const { return _children; }

    inline const LVecBase3f& get_hpr() const { return _hpr; }

    inline bool get_is_dirty() const { return _is_dirty; }

    inline const LMatrix4f& get_mat() const { return _mat; }

    inline const LVecBase3f& get_pos() const { return _pos; }

    inline const LVecBase3f& get_scale() const { return _scale; }

  protected:
    TransformComponentMeta(Entity* entity) : Component(entity)
      , _is_dirty(false)
      , _mat(LMatrix4f::ident_mat())
      , _parent(nullptr)
      , _scale({1, 1, 1})
      {};

    // AUTOGEN:: internal members
    std::vector<Entity*> _children;
    LVecBase3f _hpr;
    bool _is_dirty;
    LMatrix4f _mat;
    Entity* _parent;
    LVecBase3f _pos;
    LVecBase3f _scale;
};
#endif
